version: '3'
services:
  dataeventtrackingservice:
    container_name: dataeventtrackingservice
    image: msa-detrck
    ports:
      - 8763:8761
      - 8002:8000
      - 22419:22419
      - 22429:22429
      - 22439:22439
      - 22449:22449
      - 22459:22459
    volumes:
      - type: bind
        source: /data/DtEvtTracking/trackCmdReceiver
        target: /hdd/DtEvtTracking/trackCmdReceiver
      - type: bind
        source: /data/DtEvtTracking/trackCmdPublisher
        target: /hdd/DtEvtTracking/trackCmdPublisher
      - type: bind
        source: /data/DtEvtTracking/trackDataSub
        target: /hdd/DtEvtTracking/trackDataSub
      - type: bind
        source: /data/DtEvtTracking/trackEntTrigger
        target: /hdd/DtEvtTracking/trackEntTrigger
      - type: bind
        source: /data/DtEvtTracking/trackCmdStsChecker
        target: /hdd/DtEvtTracking/trackCmdStsChecker
    env_file: .env.prod
    networks:
      - detrck-network
    restart: unless-stopped
  rabbitmq:
    container_name: rabbitmq_detrck
    image: rabbitmq:3.7.14-management-alpine 
    volumes:
      - /hdd/rabbitmq/data/detrck/:/var/lib/rabbitmq/mnesia
      - /hdd/rabbitmq/logs/detrck:/var/log/rabbitmq/
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5674:5672" 
      - "15674:15672"
      - "25674:25672" 
      - "4371:4369"
      - "5669:5671"
      - "15669:15671"
      - "1885:1883"
      - "8885:8883"
      - "61617:61613"
      - "61618:61614"
    networks:
      - detrck-network
    restart: unless-stopped
  mariadb:
    image: mariadb:10
    ports:
      - 21219:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - /hdd/dataTest/mariadb3:/hdd/data/mariadb
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - detrck-network
    restart: unless-stopped
networks:
 detrck-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1






